ALTER TABLE core_vars
    ADD COLUMN title VARCHAR;

ALTER TABLE core_vars
    ADD COLUMN hidden BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE core_vars
    ADD COLUMN editable BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE core_vars
    ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE core_vars
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW();